[build-system]
requires = [
    "setuptools>=42",    # Ensure you have a modern version of setuptools
    "cmake",              # CMake is needed to build C++ extensions
    "pybind11",           # pybind11 to expose C++ code to Python
]
build-backend = "setuptools.build_meta"

[project]
name = "topolosses"
version = "0.0.33"
description = "A collection of losses and metrics for topology-preserving image segmentation."
readme = "topolosses/README.md"
requires-python = ">=3.7"
license = {file = "LICENSE"}
authors = [
    { name = "Janek Falkenstein", email = "j.falkenstein@tum.de" }
]
dependencies = [
    "torch>=1.9"
]
classifiers = [
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
]

[project.urls]
Repository = "https://github.com/J-falkenstein/topolosses"