name: Build Wheels

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel
          
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          # Skip musllinux and PyPy on macOS (PyPy has limited macOS support)
          CIBW_SKIP: "*-musllinux* pp*-macosx*"
          
          # Linux-specific settings
          CIBW_ARCHS_LINUX: "x86_64"
          
          # macOS-specific settings
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ENVIRONMENT_MACOS: >
            MACOSX_DEPLOYMENT_TARGET=10.14
          

          
          # macOS dependencies (using Homebrew and conda)
          CIBW_BEFORE_ALL_MACOS: >
            brew install boost &&
            brew install eigen &&
            brew install llvm libomp &&
            curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh &&
            bash Miniconda3-latest-MacOSX-x86_64.sh -b -p $HOME/miniconda &&
            export PATH=$HOME/miniconda/bin:$PATH &&
            source $HOME/miniconda/bin/activate &&
            $HOME/miniconda/bin/conda install -y -c conda-forge opencv
      
      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl