name: Build Wheel - Manually Triggered

on:
  workflow_dispatch:  # This allows you to manually trigger the build from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest  # Run on a fresh Ubuntu environment

    container:
      image: quay.io/pypa/manylinux_2_28_x86_64  # Use the manylinux base image
      options: --user root  # Run as root to install dependencies

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.18'

      # Step 3: Install build dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel 

      - name: Install dependencies
        run: |
          # Install necessary dependencies inside the container
          yum install -y \
            cmake \
            git \
            python3-dev \
            gcc-c++ \
            libopencv-devel \
            boost-devel \
            eigen3-devel \
            libomp-devel

      # Step 4: Build the wheel using cibuildwheel and the pyproject.toml file
      - name: Build Wheel using cibuildwheel
        run: |
          cibuildwheel --output-dir dist