name: Format Code

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: project-monai/monai-code-formatter@master
        with:
          format_args: "--line-length 88"
          email: "j.falkenstein@tum.de"
          username: "J-falkenstein"
          message: "Auto-format code using Black with monai formatter"
          token: ${{ secrets.GITHUB_TOKEN }}
